spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dsiApp
spring.datasource.username=aliazgorrumi
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Debug logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.dsi.ruet.backend=DEBUG