spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/DSiApp
spring.datasource.username=postgre
spring.datasource.password=ask.1023
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect