spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dsiApp
spring.datasource.username=postgre
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev